- name: Deploy Log Scraper Script to Worker Nodes
  hosts: targets
  become: yes
  tasks:
    - name: Install PyMySQL (Required for MySQL module)
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Ensure log scraper directory exists
      file:
        path: /opt/log_scraper
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy log scraper script to worker nodes
      copy:
        src: /etc/ansible/files/log_scraper.py
        dest: /opt/log_scraper/log_scraper.py
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Ensure MySQL is installed
      apt:
        name: mysql-server
        state: present
        update_cache: yes

    - name: Set MySQL root password and enable password authentication
      command: >
        mysql -u root -e "
        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root_password';
        FLUSH PRIVILEGES;"
      become: yes

    - name: Create MySQL database (logs_db)
      mysql_db:
        name: logs_db
        state: present
        login_user: root
        login_password: root_password

    - name: Create MySQL user for log storage
      mysql_user:
        name: log_user
        password: log_password
        priv: "logs_db.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: root_password

    - name: Schedule log scraper with cron
      cron:
        name: "Run Log Scraper"
        job: "python3 /opt/log_scraper/log_scraper.py"
        minute: "*/5"