- name: Install Python and MySQL
  hosts: monitoring
  become: yes
  tasks:
    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install PyMySQL (Required for Ansible MySQL module)
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is running
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password and enable password authentication
      command: |
        mysql -u root -e "
        ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root_password';
        FLUSH PRIVILEGES;"
      become: yes

    - name: Create MySQL database (logs_db)
      mysql_db:
        name: logs_db
        state: present
        login_user: root
        login_password: root_password

    - name: Create MySQL user for log storage
      mysql_user:
        name: log_user
        password: log_password
        priv: "logs_db.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: root_password

    - name: Clean up unnecessary files
      apt:
        autoclean: yes
        autoremove: yes

    - name: Remove temporary files
      file:
        path: /tmp/*
        state: absent